package kz.iitu.itse1910.nurlan.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import javax.validation.constraints.Size;
import java.io.Serializable;

@Data
public class UserDto implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(name = "id",required = false,hidden = false, example = "123", notes = "user's unique code.It's autogenerated")
    private  int id;

    @NotEmpty(message = "Name cannot be null")
    @NotNull(message = "Name cannot be null")
    @Size(min = 1, max = 16, message = "There must be at least 1 symbol, " +
            "and no more than 16")
    @ApiModelProperty(name = "Firstname",required = true, example = "Nurlan", notes = "user's firstname")
    private  String first;

    @NotEmpty(message = "Name cannot be null")
    @NotNull(message = "Name cannot be null")
    @Size(min = 1, max = 16, message = "There must be at least 1 symbol, " +
            "and no more than 16")
    @ApiModelProperty(name = "Lastname",required = true, example = "Oibekuly", notes = "user's lastname")
    private  String last;

    @Positive
    private  int age;
    private  String username;

    private byte[] photo;
}
