package kz.iitu.itse1910.nurlan.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.AssertTrue;

@Data
@NoArgsConstructor
@Entity
@Table(name = "customers")
public class Customers {

    @Id
    @ApiModelProperty(name = "customer_id",required = false,hidden = false, example = "123", notes = "customers's unique code.It's autogenerated")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private int customer_id;

    @Column(name = "firstname")
    private String firstname;

    @Column(name = "lastname")
    private String lastname;


    @Column(name = "address")
    private String address;

    @Column(name = "city")
    private String city;

    @Column(name = "phoneno")
    private String phoneno;

    public Customers(String firstname, String lastname, String address, String city, String phoneno) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.address = address;
        this.city = city;
        this.phoneno = phoneno;
    }

    public Customers(int customer_id, String firstname, String lastname, String address, String city, String phoneno) {
        this.customer_id = customer_id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.address = address;
        this.city = city;
        this.phoneno = phoneno;
    }

    public Customers(int customer_id) {
        this.customer_id = customer_id;
    }

    @Override
    public String toString() {
        return "Customers{" +
                "customer_id=" + customer_id +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", address='" + address + '\'' +
                ", city='" + city + '\'' +
                ", phoneno='" + phoneno + '\'' +
                '}';
    }



}











